---
# task/install file for hashicorp_nomad
- name: "Configure hashicorp repository"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_repositories
  vars:
    manage_repositories_enable_default_repo: false
    manage_repositories_enable_custom_repo: true
    manage_repositories_custom_repo: "{{ hashicorp_nomad_repository }}"

- name: "Install nomad:{{ hashicorp_nomad_version }}"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ hashicorp_nomad_packages }}"

- name: "Copy systemd service file for nomad"
  ansible.builtin.template:
    src: "nomad.service.j2"
    dest: "/etc/systemd/system/nomad.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - "systemctl-daemon-reload"
