---
# task/main file for hashicorp_nomad
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install.yml"
  ansible.builtin.include_tasks: install.yml
  when: hashicorp_nomad_install

- name: "Import cni_install.yml"
  ansible.builtin.include_tasks: cni_install.yml
  when: hashicorp_nomad_cni_plugins_install

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml
