---
# task/merge_variables file for hashicorp_nomad
- name: "Nomad | Merge stringified configuration"
  vars:
    _config_to_merge: "{{ hashicorp_nomad_configuration_string }}"
  ansible.builtin.set_fact:
    hashicorp_nomad_configuration: "{{
      hashicorp_nomad_configuration |
      combine(_config_to_merge|from_yaml, recursive=true)
      }}"

- name: "Nomad | Merge addresses configuration"
  vars:
    _config_to_merge: "{{ hashicorp_nomad_address_configuration }}"
  ansible.builtin.set_fact:
    hashicorp_nomad_configuration: "{{
      hashicorp_nomad_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "Nomad | Merge consul integration configuration"
  when:
    - hashicorp_nomad_enable_consul_integration | bool
  block:
    - name: "Nomad | Merge consul tls configuration"
      when:
        - hashicorp_nomad_consul_integration_configuration.ssl is defined
        - hashicorp_nomad_consul_integration_configuration.ssl | bool
      block:
        - name: "Nomad | Merge consul default client configuration"
          vars:
            _config_to_merge: "{{ hashicorp_nomad_consul_integration_tls_configuration }}"
          ansible.builtin.set_fact:
            hashicorp_nomad_consul_integration_configuration: "{{
              hashicorp_nomad_consul_integration_configuration |
              combine(_config_to_merge, recursive=true)
              }}"

    - name: "Nomad | Merge consul configuration for nomad servers"
      when:
        - hashicorp_nomad_enable_server
      block:
        - name: "Nomad | Merge consul default server configuration"
          vars:
            _config_to_merge: "{{ hashicorp_nomad_consul_integration_server_configuration }}"
          ansible.builtin.set_fact:
            hashicorp_nomad_consul_integration_configuration: "{{
              hashicorp_nomad_consul_integration_configuration |
              combine(_config_to_merge, recursive=true)
              }}"

    - name: "Nomad | Merge consul configuration for nomad clients"
      when:
        - hashicorp_nomad_enable_client
      block:
        - name: "Nomad | Merge consul default client configuration"
          vars:
            _config_to_merge: "{{ hashicorp_nomad_consul_integration_client_configuration }}"
          ansible.builtin.set_fact:
            hashicorp_nomad_consul_integration_configuration: "{{
              hashicorp_nomad_consul_integration_configuration |
              combine(_config_to_merge, recursive=true)
              }}"

        - name: "Nomad | Merge consul tls client configuration"
          vars:
            _config_to_merge: "{{ hashicorp_nomad_consul_integration_client_tls_configuration }}"
          ansible.builtin.set_fact:
            hashicorp_nomad_consul_integration_configuration: "{{
              hashicorp_nomad_consul_integration_configuration |
              combine(_config_to_merge, recursive=true)
              }}"
          when:
            - hashicorp_nomad_consul_integration_configuration.ssl is defined
            - hashicorp_nomad_consul_integration_configuration.ssl | bool

    - name: "Nomad | Merge consul block into main configuration"
      vars:
        _config_to_merge:
          consul: "{{ hashicorp_nomad_consul_integration_configuration }}"
      ansible.builtin.set_fact:
        hashicorp_hashicorp_nomad_configuration: "{{
          hashicorp_hashicorp_nomad_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

- name: "Nomad | Merge TLS configuration"
  when: hashicorp_nomad_enable_tls | bool
  block:
    - name: "Nomad | Merge TLS configuration"
      vars:
        _config_to_merge:
          tls: "{{ hashicorp_nomad_tls_configuration }}"
      ansible.builtin.set_fact:
        hashicorp_nomad_configuration: "{{
          hashicorp_nomad_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "Nomad | Add certificates directory to extra_files_dir"
      ansible.builtin.set_fact:
        hashicorp_nomad_extra_files_list: "{{
          hashicorp_nomad_extra_files_list +
          hashicorp_nomad_certificates_extra_files_dir
          | unique
          | sort
          }}"

- name: "Nomad | Merge plugin configuration"
  vars:
    _config_to_merge:
      plugin: "{{
        hashicorp_nomad_driver_configuration |
        combine(hashicorp_nomad_driver_extra_configuration, recursive=true)
        }}"
  ansible.builtin.set_fact:
    hashicorp_nomad_configuration: "{{
      hashicorp_nomad_configuration |
      combine(_config_to_merge, recursive=true)
      }}"
  when: hashicorp_nomad_enable_client | bool

- name: "Nomad | Merge extra configuration settings"
  vars:
    _config_to_merge: "{{ hashicorp_nomad_extra_configuration }}"
  ansible.builtin.set_fact:
    hashicorp_nomad_configuration: "{{
      hashicorp_nomad_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "Nomad | Merge log to file configuration"
  vars:
    _config_to_merge: "{{ hashicorp_nomad_log_to_file_configuration }}"
  ansible.builtin.set_fact:
    hashicorp_nomad_configuration: "{{
      hashicorp_nomad_configuration |
      combine(_config_to_merge, recursive=true)
      }}"
  when: hashicorp_nomad_enable_log_to_file
