---
# task/prerequisites file for hashicorp_nomad
- name: "Install pre-required system packages"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ hashicorp_nomad_required_packages }}"

- name: "Create group {{ hashicorp_nomad_group }}"
  ansible.builtin.group:
    name: "{{ hashicorp_nomad_user }}"
    state: present

- name: "Create user {{ hashicorp_nomad_user }}"
  ansible.builtin.user:
    name: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    shell: /bin/false
    state: present

- name: "Create directory {{ hashicorp_nomad_config_dir }}"
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_config_dir }}"
    state: directory
    owner: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    mode: "0755"

- name: "Create directory {{ hashicorp_nomad_data_dir }}"
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_data_dir }}"
    state: directory
    owner: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    mode: "0755"
