---
# task/prerequisites file for hashicorp_nomad
- name: "Nomad | Create group {{ hashicorp_nomad_group }}"
  ansible.builtin.group:
    name: "{{ hashicorp_nomad_user }}"
    state: present

- name: "Nomad | Create user {{ hashicorp_nomad_user }}"
  ansible.builtin.user:
    name: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    shell: /bin/false
    state: present

- name: "Nomad | Create directory {{ hashicorp_nomad_config_dir }}"
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_config_dir }}"
    state: directory
    owner: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    mode: "0755"

- name: "Nomad | Create directory {{ hashicorp_nomad_data_dir }}"
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_data_dir }}"
    state: directory
    owner: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    mode: "0755"

- name: "Nomad | Create directory {{ hashicorp_nomad_certs_dir }}"
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_certs_dir }}"
    state: directory
    owner: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    mode: "0755"

- name: "Nomad | Create directory {{ hashicorp_nomad_logs_dir }}"
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_logs_dir }}"
    state: directory
    owner: "{{ hashicorp_nomad_user }}"
    group: "{{ hashicorp_nomad_group }}"
    mode: "0755"
  when: hashicorp_nomad_enable_log_to_file
